# Generated by Django 5.2.4 on 2025-10-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('height', models.FloatField(help_text='Height in cm')),
                ('waist_circumference', models.FloatField(help_text='Waist circumference in cm')),
                ('health_goal', models.TextField()),
                ('duration', models.IntegerField(blank=True, help_text='Duration in weeks (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_response', models.TextField()),
            ],
        ),
    ]
