# Generated by Django 5.2.4 on 2025-10-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessassessment',
            name='food_preference',
            field=models.CharField(choices=[('ANY', 'No Preference'), ('INDIAN', 'Indian'), ('AMERICAN', 'American'), ('MEXICAN', 'Mexican'), ('ASIAN', 'Asian'), ('MEDITERRANEAN', 'Mediterranean'), ('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan')], default='ANY', max_length=20),
        ),
        migrations.AddField(
            model_name='fitnessassessment',
            name='workout_place',
            field=models.CharField(choices=[('ANY', 'No Preference'), ('HOME', 'At Home'), ('GYM', 'Gym'), ('PARK', 'Park/Outdoors'), ('ANY_OUTDOOR', 'Any Outdoor'), ('ANY_INDOOR', 'Any Indoor')], default='ANY', max_length=20),
        ),
    ]
